/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.CarMakers;

/**
 *
 * @author carlo
 */
public class JF_gui_main extends javax.swing.JFrame {

    /**
     * Creates new form JF_gui_main
     */
    JF_gui_CarDetails cDetail;
    JF_gui_CarMakers cMakers;
    JF_gui_CarNames cNames;
    JF_gui_ModelDetails mDetails;
    JF_gui_Countries countries;
    JF_gui_Continents continents;

    public JF_gui_main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCarMakers = new javax.swing.JButton();
        btnCarDetails = new javax.swing.JButton();
        btnCarNames = new javax.swing.JButton();
        btnContinents = new javax.swing.JButton();
        btnCountries = new javax.swing.JButton();
        btnModelDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCarMakers.setText("Car_Makers");
        btnCarMakers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarMakersActionPerformed(evt);
            }
        });

        btnCarDetails.setText("Car_Details");
        btnCarDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarDetailsActionPerformed(evt);
            }
        });

        btnCarNames.setText("Car_Names");
        btnCarNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarNamesActionPerformed(evt);
            }
        });

        btnContinents.setText("Continents");
        btnContinents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinentsActionPerformed(evt);
            }
        });

        btnCountries.setText("Countries");
        btnCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountriesActionPerformed(evt);
            }
        });

        btnModelDetails.setText("Model_Details");
        btnModelDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarMakers, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(btnContinents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(btnCountries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModelDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCarDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCountries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCarNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCarMakers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnContinents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarMakersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarMakersActionPerformed
        cMakers = new JF_gui_CarMakers();
        cMakers.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCarMakersActionPerformed

    private void btnModelDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelDetailsActionPerformed
        mDetails = new JF_gui_ModelDetails();
        mDetails.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModelDetailsActionPerformed

    private void btnCarDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarDetailsActionPerformed
        cDetail = new JF_gui_CarDetails();
        cDetail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCarDetailsActionPerformed

    private void btnCarNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarNamesActionPerformed
        cNames = new JF_gui_CarNames();
        cNames.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCarNamesActionPerformed

    private void btnContinentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinentsActionPerformed
        continents = new JF_gui_Continents();
        continents.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContinentsActionPerformed

    private void btnCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountriesActionPerformed
        countries = new JF_gui_Countries();
        countries.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCountriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_gui_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarDetails;
    private javax.swing.JButton btnCarMakers;
    private javax.swing.JButton btnCarNames;
    private javax.swing.JButton btnContinents;
    private javax.swing.JButton btnCountries;
    private javax.swing.JButton btnModelDetails;
    // End of variables declaration//GEN-END:variables
}
